export const skills = [
  { content: "HTML: semantics, accessibility" },
  { content: "CSS Flexbox" },
  { content: "CSS Grid" },
  { content: "BEM convention" },
  { content: "JavaScript: ES6+" },
  { content: "Promises, async/await" },
  { content: "Local Storage" },
  { content: "Fetch, Axios" },
  { content: "Error handling" },
  { content: "Markdown" },
  { content: "Immutability" },
  { content: "React" },
  { content: "React Hooks" },
  { content: "React Router" },
  { content: "Redux (Toolkit)" },
  { content: "Redux Saga" },
  { content: "NPM" },
  { content: "Git" },
  { content: "Scrum" },
  { content: "Teamwork" },
]